-- Usunięcie tabel CUSTOMERS i ORDERS (jeśli istnieją)
DROP TABLE CUSTOMERS;
DROP TABLE ORDERS;
/

-- Utworzenie tabel CUSTOMERS i ORDERS
CREATE TABLE CUSTOMERS (
	customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR2(100) NOT NULL,
	surname VARCHAR2(100) NOT NULL,
	address VARCHAR2(255) NOT NULL,
	CONSTRAINT pk_customers PRIMARY KEY (customer_id)
);
CREATE TABLE ORDERS (
	order_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	product VARCHAR2(100) NOT NULL,
	cnt NUMBER NOT NULL,
	price NUMBER(10, 2) NOT NULL,
	customer_id NUMBER NOT NULL,
	CONSTRAINT pk_orders PRIMARY KEY (order_id),
	CONSTRAINT fk_orders_customers FOREIGN KEY (customer_id) REFERENCES CUSTOMERS(customer_id)
);
/

-- Deklaracja pakietu
CREATE OR REPLACE PACKAGE JSON_PARSER_PKG AS
	PROCEDURE INSERT_ORDERS_FROM_JSON(p_json IN CLOB);
END JSON_PARSER_PKG;
/

-- Definicja pakietu
CREATE OR REPLACE PACKAGE BODY JSON_PARSER_PKG AS
	PROCEDURE INSERT_ORDERS_FROM_JSON(p_json IN CLOB)
	IS
		v_customer_id NUMBER;
	BEGIN
		-- Wstawienie klienta do tabeli CUSTOMERS
		INSERT INTO CUSTOMERS (name, surname, address)
		VALUES (
			JSON_VALUE(p_json, '$.klient.imie' RETURNING VARCHAR2),
			JSON_VALUE(p_json, '$.klient.nazwisko' RETURNING VARCHAR2),
			JSON_VALUE(p_json, '$.klient.adres' RETURNING VARCHAR2)
		)
		RETURNING customer_id INTO v_customer_id;

		-- Wstawienie zamówień do tabeli ORDERS
		FOR rec IN (
			SELECT product, cnt, price
			FROM JSON_TABLE(p_json, '$.zamowienia[*]'
				COLUMNS (
					product VARCHAR2(100) PATH '$.produkt',
					cnt NUMBER PATH '$.ilosc',
					price NUMBER PATH '$.cena'
				)
			)
		) LOOP
			INSERT INTO ORDERS (product, cnt, price, customer_id)
			VALUES (rec.product, rec.cnt, rec.price, v_customer_id);
		END LOOP;
	END INSERT_ORDERS_FROM_JSON;
END JSON_PARSER_PKG;
/

DECLARE
	v_json CLOB := '{
		"klient": {
			"imie": "Jan",
			"nazwisko": "Kowalski",
			"adres": "ul. Testowa 123, 00-000 Warszawa"
		},
		"zamowienia": [
			{
				"produkt": "Laptop",
				"ilosc": 1,
				"cena": 3500.00
			},
			{
				"produkt": "Smartphone",
				"ilosc": 2,
				"cena": 1500.00
			},
			{
				"produkt": "Słuchawki bezprzewodowe",
				"ilosc": 1,
				"cena": 200.00
			}
		]
	}';
BEGIN
	JSON_PARSER_PKG.INSERT_ORDERS_FROM_JSON(v_json);
END;
/

SELECT * FROM customers;
SELECT * FROM orders;
